version: "3.7"
services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
    ports:
      - 3030:3000

  node-exporter:
    image: prom/node-exporter:v1.0.1
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - 9099:9090
