global:
  scrape_interval: 30s
rule_files:
scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['192.168.100.1:7001']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']