version: '3'
services:
  zookeeper:
    image: arm64v8/zookeeper:latest
    ports:
      - 2181:2181

  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - 9092:9092
    expose:
      - 9092
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092

  web-ui:
    image: docker.redpanda.com/vectorized/console:latest
    ports:
      - 8082:8080
    environment:
      - KAFKA_BROKERS=kafka:9092
